/**
 * This class is generated by jOOQ
 */
package jooq.airdrone;


import javax.annotation.Generated;

import jooq.airdrone.tables.Rating;
import jooq.airdrone.tables.User;


/**
 * Convenience access to all tables in airdrone
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>airdrone.Rating</code>.
     */
    public static final Rating RATING = jooq.airdrone.tables.Rating.RATING;

    /**
     * The table <code>airdrone.User</code>.
     */
    public static final User USER = jooq.airdrone.tables.User.USER;
}
