/**
 * This class is generated by jOOQ
 */
package jooq.airdrone.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.airdrone.Airdrone;
import jooq.airdrone.Keys;
import jooq.airdrone.tables.records.RatingRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rating extends TableImpl<RatingRecord> {

    private static final long serialVersionUID = 1982613874;

    /**
     * The reference instance of <code>airdrone.Rating</code>
     */
    public static final Rating RATING = new Rating();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RatingRecord> getRecordType() {
        return RatingRecord.class;
    }

    /**
     * The column <code>airdrone.Rating.idRating</code>.
     */
    public final TableField<RatingRecord, Integer> IDRATING = createField("idRating", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>airdrone.Rating.idUser</code>.
     */
    public final TableField<RatingRecord, Integer> IDUSER = createField("idUser", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>airdrone.Rating.rating</code>.
     */
    public final TableField<RatingRecord, Integer> RATING_ = createField("rating", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>airdrone.Rating</code> table reference
     */
    public Rating() {
        this("Rating", null);
    }

    /**
     * Create an aliased <code>airdrone.Rating</code> table reference
     */
    public Rating(String alias) {
        this(alias, RATING);
    }

    private Rating(String alias, Table<RatingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rating(String alias, Table<RatingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Airdrone.AIRDRONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RatingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RatingRecord> getPrimaryKey() {
        return Keys.KEY_RATING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RatingRecord>> getKeys() {
        return Arrays.<UniqueKey<RatingRecord>>asList(Keys.KEY_RATING_PRIMARY, Keys.KEY_RATING_IDRATING_UNIQUE, Keys.KEY_RATING_IDUSER_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RatingRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RatingRecord, ?>>asList(Keys.FK_IDUSER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rating as(String alias) {
        return new Rating(alias, this);
    }

    /**
     * Rename this table
     */
    public Rating rename(String name) {
        return new Rating(name, null);
    }
}
