/**
 * This class is generated by jOOQ
 */
package jooq.airdrone.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.airdrone.Airdrone;
import jooq.airdrone.Keys;
import jooq.airdrone.tables.records.RatingRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rating extends TableImpl<RatingRecord> {

    private static final long serialVersionUID = -48962819;

    /**
     * The reference instance of <code>airdrone.rating</code>
     */
    public static final Rating RATING = new Rating();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RatingRecord> getRecordType() {
        return RatingRecord.class;
    }

    /**
     * The column <code>airdrone.rating.idrating</code>.
     */
    public final TableField<RatingRecord, Integer> IDRATING = createField("idrating", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('airdrone.rating_idrating_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>airdrone.rating.email</code>.
     */
    public final TableField<RatingRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>airdrone.rating.rating</code>.
     */
    public final TableField<RatingRecord, Integer> RATING_ = createField("rating", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>airdrone.rating</code> table reference
     */
    public Rating() {
        this("rating", null);
    }

    /**
     * Create an aliased <code>airdrone.rating</code> table reference
     */
    public Rating(String alias) {
        this(alias, RATING);
    }

    private Rating(String alias, Table<RatingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rating(String alias, Table<RatingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Airdrone.AIRDRONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RatingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RatingRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RatingRecord, ?>>asList(Keys.RATING__RATING_EMAIL_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rating as(String alias) {
        return new Rating(alias, this);
    }

    /**
     * Rename this table
     */
    public Rating rename(String name) {
        return new Rating(name, null);
    }
}
