/**
 * This class is generated by jOOQ
 */
package jooq.airdrone.tables.records;


import javax.annotation.Generated;

import jooq.airdrone.tables.Rating;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingRecord extends TableRecordImpl<RatingRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -1753803477;

    /**
     * Setter for <code>airdrone.rating.idrating</code>.
     */
    public void setIdrating(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>airdrone.rating.idrating</code>.
     */
    public Integer getIdrating() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>airdrone.rating.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>airdrone.rating.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>airdrone.rating.rating</code>.
     */
    public void setRating(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>airdrone.rating.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Rating.RATING.IDRATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Rating.RATING.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Rating.RATING.RATING_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdrating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingRecord value1(Integer value) {
        setIdrating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingRecord value2(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingRecord value3(Integer value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RatingRecord
     */
    public RatingRecord() {
        super(Rating.RATING);
    }

    /**
     * Create a detached, initialised RatingRecord
     */
    public RatingRecord(Integer idrating, String email, Integer rating) {
        super(Rating.RATING);

        set(0, idrating);
        set(1, email);
        set(2, rating);
    }
}
